theme: jekyll-theme-minimal
title: Platron
description: A graphical manager for ADB and fastboot
show_downloads: true
github: 
  zip_url: https://github.com/platron-pt/platron/releases/latest/download/Easy-ADB-and-fastboot-win-x64.exe
  tar_url: https://github.com/platron-pt/platron/releases/latest/download/Easy-ADB-and-fastboot-linux-x64.tar.xz
  repository_url: https://github.com/platron-pt/platron
  repository_nwo: platron-pt/platron
