theme: jekyll-theme-minimal
title: Easy ADB and fastboot (EAF)
description: a GUI tool for easier using ADB and fastboot
show_downloads: true
github: 
  zip_url: https://github.com/ryantsui1109/eaf-binary/releases/latest/download/setup.exe
  tar_url: https://github.com/ryantsui1109/eaf-binary/releases/latest/download/easy_adb_fastboot-linux.tar.xz
  repository_url: https://github.com/ryantsui1109/Easy_ADB_fastboot
  repository_nwo: ryantsui1109/Easy_ADB_fastboot
